### ISSUE TITLE
RadialStatus

### ISSUE THREAD

**Issue by foqlol** [KewlSage/bordershapes#1]
is there a way to disable the radial status theme?

**Comment by KewlSage** [comment]
sorry for the wait, no unfortunately, I did just push a fix for the small issue with user pop-out avatars though.

**Comment by foqlol** [comment]
alright thank you for answering

**Comment by KewlSage** [comment]
I replaced it entirely earlier so yay! (the mobile indicator was annoying).

**Comment by man-of-eel** [comment]
Please stop naming your commit messages things like 'poggers' 'oops' and 'that worked i think' my god

**Comment by KewlSage** [comment]
Ok, how about a random letter instead?
