### ISSUE TITLE
Dot status indicators

### ISSUE THREAD

**Issue by man-of-eel** [KewlSage/bordershapes#2]
![image](https://user-images.githubusercontent.com/86927456/149039391-0a8fd461-8170-4a5e-be98-27e3b8734eec.png)

How can I disable these?

**Comment by KewlSage** [comment]
do you want to remove them or relocate them?

**Comment by KewlSage** [comment]
The CSS that modifies the status indicators is everything in lines 761 to 832, it would be easier to fork the theme and remove those lines for your self, that will result in this: 
![image](https://user-images.githubusercontent.com/46802123/149273702-c1fefc88-7f2f-447f-b64e-15459ceb73a3.png)

however i noticed you had a fork before wishing to bring back the radial statuses, if that is what you actually want than simply add this to your downloaded theme under the base import or custom css
```css
@import url(https://kewlsage.github.io/BorderShapes/addons/radial-statuses.css);
```
